language: elixir
matrix:
  include:
    - elixir: 1.6.6
      otp_release: 20.3.8.5
    - elixir: 1.6.6
      otp_release: 21.1.4
    - elixir: 1.7.3
      otp_release: 20.3.8.5
    - elixir: 1.7.3
      otp_release: 21.1.4
    - elixir: 1.7.4
      otp_release: 21.1.4
    - elixir: 1.8.1
      otp_release: 21.1.4
script: "epmd -daemon && MIX_ENV=test mix do deps.get, coveralls.travis"
